### ISSUE TITLE
Add travis.yml for continous integration

### ISSUE THREAD

**Issue by mbalex99** [getditto/safer_ffi#2]
- [ ] Add continuous integration with travis.yml
- [ ] Allow travis to generate github pages

**Comment by danielhenrymantilla** [comment]
Since this was a Github -> Github thing (from Github sources to Github pages), I've taken the liberty to cut the middle man and implement the functionality through Github Actions rather than Travis: https://github.com/getditto/safer_ffi/commit/1806470afe72082c55f6af96b14e41150d874fce#diff-fc6988097954f601e9f877d8b1b5baa2

  - (Tested with https://github.com/getditto/safer_ffi/commit/59cc92c5fb6029e0b53a5a7fb9c3e08d8f46cd0e)

I am thus closing this as resolved, but feel free to reopen if, for instance, using Travis was imperative.
