### ISSUE TITLE
Encountered a compiler panic

### ISSUE THREAD

**Issue by okpatil4u** [getditto/safer_ffi#25]
I have [reported](https://github.com/rust-lang/rust/issues/79894) it to official rust repository

**Comment by danielhenrymantilla** [comment]
Yeah, it's quite unfortunate that this regression was introduced and yet the fix is taking quite long (too long?) to land on stable rust. I'll repeat the workaround here:

> The issue has been fixed in latest `nightly`, and I think that in latest `beta` too, sadly it hasn't yet landed on stable, we will have to wait for the nest stable `release` in January.

So the current workaround is to pin the compiler version to _before_ the regression (`1.46.0`) or to _after_ the fix (`beta` _i.e._, ≥ `1.49.0`).
