### ISSUE TITLE
Compatibility with serde

### ISSUE THREAD

**Issue by david-bouyssie** [getditto/safer_ffi#35]
I'm trying to define a struct that I'm using for serialization/deserialization with Serde like this:

```rust
use serde::{Deserialize, Serialize};

#[derive_ReprC]
#[repr(C)]
#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
pub
struct Point {
    #[serde(rename = "x_value")] 
    x: f64,
    #[serde(rename = "y_value")] 
    y: f64,
}
```

However "safer_ffi" macros seem to generate a conflict since I get the following error at compile time:
```cannot find attribute `serde` in this scope```

I guess that since #[derive()] is not executed last, some definitions are missing in a previous stage?

**Comment by danielhenrymantilla** [comment]
Thanks for reporting it. The problem lies in:

https://github.com/getditto/safer_ffi/blob/5172c1b2cb2bdb5b2b8ca085ed75918d713d45a8/src/layout/macros.rs#L388

which is basically the code for the "raw" variant / aspect of the `ReprC` struct (since `ReprC` defines a mapping from the higher-level Rust type to a raw `#[repr(C)]` version of it with no safety invariants attached to it).

  - <img width="439" alt="Screen Shot 2021-02-22 at 18 33 30" src="https://user-images.githubusercontent.com/9920355/108746341-7f59a100-753c-11eb-8cc7-8bcd947ce86d.png">

And from the code there (modulo macro readability), we can see this raw variant only gets its doc comments forwarded, but not the other ones (because it shouldn't be necessary to have other macros applied to that raw variant, and as we can see here, forwarding macros to things that are not the originally written struct can cause problems).

And the oversight here is that the field attributes are still forwarded!

So not-forwarding the latter ought to fix the issue. I don't have time to make sure this fix won't cause breakage elsewhere (misinteraction between multiple macros is very common and with edge cases everywhere), so I won't merge the PR and make an official release with it yet. But you should be able to use that version using [a Cargo `[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section):

```toml
[patch.crates-io.safer-ffi]
version = "0.0.5"
branch = "fix/derive_repr_c_and_other_macros"
```

**Comment by david-bouyssie** [comment]
Amazing, so fast you are!

Thanks. Will try ASAP.
