### ISSUE TITLE
Does char_p::Box implement AsRef<str>?

### ISSUE THREAD

**Issue by eutampieri** [getditto/safer_ffi#81]
Trying to compile this:
```rust
struct Shift{}
pub trait GenericCollectionShift<S: Sized + Send + Sync + PartialEq + AsRef<str>> {
}
impl GenericCollectionShift<char_p::Box> for Shift {
}
```
works on macOS but fails on Ubuntu.
I'm getting
```
116 | impl GenericCollectionShift<char_p::Box> for Shift {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRef<str>` is not implemented for `char_p_boxed`
    |
note: required by a bound in `GenericCollectionShift`
   --> src/types.rs:13:71
    |
13  | pub trait GenericCollectionShift<S: Sized + Send + Sync + PartialEq + AsRef<str>> {
    |                                                                       ^^^^^^^^^^ required by this bound in `GenericCollectionShift`
```

**Comment by danielhenrymantilla** [comment]
> works on macOS 

Hmm, that is weird: `char_p::Box` does indeed not implement `AsRef<str>` currently, for similary-ish reasons to stdlib's `CStr` not being `AsRef<[u8]>`: the operation is not constant (it needs to scan for the null-byte), and it is unclear whether the terminating null byte should be included in the output.

Note that I have no strong opinions on this, so I don't mind being convinced otherwise.

That being said, since `char_p::Box` does have an `.into_string()` method, which converts it into a `String` **by reusing the allocation / in a zero-copy manner** (it just `.pop()`s the terminating null byte), you could try to convert the `char_p::Box`es into `String`s beforehand if that is possible for you to do.

Otherwise you can also write your own wrapper type:

```rust
/// Same as `char_p::Box`, but with an `AsRef<str>` implementation which
/// includes
/// does not include
// (pick one)
/// the terminating null byte.
#[derive_ReprC] #[repr(transparent)] // <- if you want to use it instead of `char_p::Box` with `#[ffi_export]`
struct MyBoxedCString(char_p::Box);

impl AsRef<str> for MyBoxedCString {
    fn as_ref(self: &Self) -> &str {
        self.0.to_str()
        // pick one
        self.0.to_str_with_null()
    }
}

impl GenericCollectionShift<MyBoxedCString> for Shift {
}
```

**Comment by danielhenrymantilla** [comment]
Hmm, there is an `.into_string()` operation, but no `Into<String>` impl. That one is very legitimate to add, so I may very well add it in the near future. Feel free to open an issue asking for it

**Comment by eutampieri** [comment]
While I’m at it I might as well open a pr ;)

Eugenio Tampieri
